### ISSUE TITLE
Bug: /home/events page, the events detail list can't dynamic update

### ISSUE THREAD

**Issue by ryomahan** [Tracardi/tracardi-gui#57] opened 2021-11-26 06:09 UTC
**route: /home/events**

**bug detail:** 
when the filter button on /home/events is clicked, the bar charts is dynamic updated, but the events' detail info list is not updated unless the page is refreshed.

**Comment by atompie** [comment] 2021-11-26 13:57
@ryomahan Thanks for spotting this issue. This is actually a duplicate of https://github.com/Tracardi/tracardi-gui/issues/50 and we will soon make it go away. :)

**Comment by atompie** [comment] 2021-12-02 19:54
Duplicate of #50

**Comment by atompie** [comment] 2021-12-21 21:54
React.memo was removed and it solved the problem for this release.

**Closed** 2021-12-21 21:54 UTC
Labels: bug
